######################################################################
# Automatically generated by qmake (3.0) Do. Nov. 13 09:00:23 2014
######################################################################


QT       += core network

QT       -= gui

TARGET = fb-client
CONFIG   += console
CONFIG   -= app_bundle

TEMPLATE = app


SOURCES += main.cpp \
    painter.cpp \
    fbclient.cpp

HEADERS += \
    painter.h \
    fbclient.h \
    ../fb-shared/framebuffer.h
